stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
    - webmap
  script: echo "TODO auto-test"

build:
  stage: build
  tags:
    - webmap
  script:
    - 'echo "Building project..."'
    - 'call npm install'
    - 'del .env'
    - 'copy .env.production .env'
    - 'call npm run-script build'
    - 'rmdir /s /q build\explorerLite'
    - 'del /Q build\static\css\*.map'
    - 'del /Q build\static\js\*.map'
    - 'git commit -a -m "[ci skip] autocommit inc-version after build"'
    - 'git push http://tumak.aleksandr:2RQsxH5Ln5JwivqUHsG1@gitlab.intecracy.com/DZVIN/WebMap.git HEAD:develop'
    - 'echo "Done!"'
  artifacts:
    expire_in: 1 month
    paths:
      - './build/index.html'
      - './build/static/css/main.*.css'
      - './build/static/js/main.*.js'

deploy-qa:
  stage: deploy
  tags:
    - webmap
  script:
    - 'echo "Deploying to QA environment..."'
    - 'dir'
    - 'echo "Done!"'

deploy-zip:
  stage: deploy
  tags:
    - webmap
  script:
    - 'echo "Packing bundle into ZIP file..."'
    - 'dir'
    - 'echo "Done!"'
