stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
    - webmap
  script: echo "TODO auto-test"

build:
  stage: build
  tags:
  - webmap
  script: echo "TODO build project"
  artifacts:
    paths:
      - build/index.html
      - build/static/css/main.*.css
      - build/static/js/main.*.js

deploy-qa:
  stage: deploy
  tags:
  - webmap
  script: echo "TODO deploy to QA environment"

deploy-zip:
  stage: deploy
  tags:
  - webmap
  script: echo "TODO pack bundle into ZIP file"
