variables:
  exe7z: 'C:\Tools\7z\7za.exe'
  releaseDir: 'C:\Production'
  deployDir: 'MAKET\SpaceHub\WebMap'
  gitlabPath: 'gitlab.intecracy.com/DZVIN/WebMap.git'
  push_version: 'gitlab.intecracy.com/DZVIN/install_update.git'

stages:
  - build
  - deploy
  - increment-dzvin
  
.base: &base-dev
  only:
    - develop
  tags:
    - webmap-dev

.base: &base
  only:
    - master
  tags:
    - webmap-dev

build:
  stage: build
  <<: *base-dev
  script:
    - echo Building project...
    - call npm i
#    - call yarn add @DZVIN/CommonComponents @DZVIN/MilSymbolEditor
    - copy .env .env.backup
    - copy .env.production .env
    - call npm run-script build
    - rmdir /s /q build\explorerLite
    - copy .env.backup .env
    - del .env.backup
    - set jsonfile=package.json
    - set psCmd="add-type -As System.Web.Extensions;$JSON = new-object Web.Script.Serialization.JavaScriptSerializer;$JSON.DeserializeObject($input).version"
    - for /f %%I in ('^<"%jsonfile%" powershell -noprofile %psCmd%') do set "version=%%I"
    - git status
    - git commit -a -m "[CI skip] %version% (autocommit)"
    - git push https://%ACCESS_USER%:%ACCESS_TOKEN%@%gitlabPath% HEAD:develop
    - echo Done
  artifacts:
    expire_in: 1 hour
    paths:
      - ./build/index.html
      - ./build/manifest.json
      - ./build/favicon.ico
      - ./build/service-worker.js
      - ./build/asset-manifest.json
      - ./build/images/*.*
      - ./build/static/css/*.*
      - ./build/static/js/*.*
      - ./build/static/media/*.*

deploy-qa-11:
  stage: deploy
  <<: *base-dev
  cache: {}
  script:
    - echo Deploying to QA environment...
    - 'echo ========= Deploy: 11 (remote) ========='
    - xcopy /E /C /I /Q /H /R /Y build \\172.16.97.11\c$\%deployDir%


deploy-self(17):
  stage: deploy
  <<: *base-dev
  cache: {}
  script:   
    - 'echo ========= Deploy: 17 (local) ========='
    - rmdir /s /q C:\%deployDir%
    - xcopy /E /C /I /Q /H /R /Y build C:\%deployDir%
    - echo Done

Increment_dzvin_dev:
  stage: increment-dzvin
  <<: *base-dev
  script: 
    - echo run build
    - echo Done
    - cd C:\Version-dev\install_update
    - git checkout develop
    - git pull
    - powershell.exe .\Versionalyze_dev.ps1
    - powershell.exe Start-sleep -s 10
    - git commit -a -m "autocommit"
    - git push https://%PUSH_USER%:%PUSH_TOKEN%@%push_version% HEAD:develop
  dependencies: []

######################### START MASTER ##############################

build-master:
  stage: build
  <<: *base
  script:
    - echo Building project...
    - call yarn
    - call yarn add @DZVIN/CommonComponents @DZVIN/MilSymbolEditor
    - copy .env .env.backup
    - copy .env.production .env
    - call npm run-script build
    - rmdir /s /q build\explorerLite
    - echo Done
  artifacts:
    expire_in: 1 hour
    paths:
      - ./build/index.html
      - ./build/manifest.json
      - ./build/favicon.ico
      - ./build/service-worker.js
      - ./build/asset-manifest.json
      - ./build/images/*.*
      - ./build/static/css/*.*
      - ./build/static/js/*.*
      - ./build/static/media/*.*

deploy-qa29:
  stage: deploy
  <<: *base
  cache: {}
  script:
    - echo Deploying to QA environment...
    - 'echo ========= Deploy: 29 (remote) ========='
    - xcopy /E /C /I /Q /H /R /Y build \\172.16.97.29\c$\%deployDir%


deploy-qa43:
  stage: deploy
  <<: *base
  cache: {}
  script:
    - echo Deploying to QA environment...
    - 'echo ========= Deploy: 43 (remote) ========='
    - xcopy /E /C /I /Q /H /R /Y build \\172.16.97.43\c$\%deployDir%

deploy-zip:
  stage: deploy
  <<: *base
  script:
    - echo Packing bundle into ZIP file...
    - set jsonfile=package.json
    - set psCmd="add-type -As System.Web.Extensions;$JSON = new-object Web.Script.Serialization.JavaScriptSerializer;$JSON.DeserializeObject($input).version"
    - for /f %%I in ('^<"%jsonfile%" powershell -noprofile %psCmd%') do set "version=%%I"
    - 'echo Version: %version%'
    - set pack="WebmapFrontend_v%version%.zip"
    - echo %pack%
    - del /Q build\static\css\*.map
    - del /Q build\static\js\*.map
    - cd build
    - echo Zipping...
    - '"%exe7z%" a -tzip "%releaseDir%\%pack%" "*"'
    - echo "copy to remote"
    - call pscp -batch -pw %SSH_PASS% %releaseDir%\WebmapFrontend_v%version%.zip %SSH_USER_HOST%:%REMOTE_PATH%/%CURRENT_VERSION_MASTER%/

Increment_dzvin:
  stage: increment-dzvin
  <<: *base
  script:
    - echo run increment
    - echo Done
    - cd c:\Production\Version\install_update
    - git checkout master
    - git pull
    - powershell.exe .\Versionalyze.ps1
    - powershell.exe Start-sleep -s 10
    - git commit -a -m "autocommit"
    - git push https://%PUSH_USER%:%PUSH_TOKEN%@%push_version% HEAD:master
  dependencies: []