variables:
  deployDir: 'C:\C4\SpaceHub\WebMap'


stages:
  - build
  - deploy

build:
  stage: build
  only:
    - develop
  tags:
    - webpack
  before_script:
    - chcp 65001
    - git config --global user.email "tumak.oleksandr@gmail.com"
    - git config --global user.name "Oleksandr Tumak"
  script:
    - echo Incrementing version...
    - call node ./scripts/inc-version.js
    - set jsonfile=package.json
    - set psCmd="add-type -As System.Web.Extensions;$JSON = new-object Web.Script.Serialization.JavaScriptSerializer;$JSON.DeserializeObject($input).version"
    - for /f %%I in ('^<"%jsonfile%" powershell -noprofile %psCmd%') do set "version=%%I"
    - call npm install
    #- call npm install @C4/blank-editor@latest @C4/EuSign@latest @C4/validators@latest @C4/CommonComponents@latest @C4/MilSymbolEditor@latest @C4/components@latest
    - copy .env .env.backup
    - copy .env.production .env
    - set NODE_OPTIONS="--max-old-space-size=8192"
    - call npm run svg-sprite2
    - call npm run build
    - copy .env.backup .env
    - del /q .env.backup
    - git status
    - git commit -a -m "[CI skip] %version% (autocommit)"
    - git push https://%ACCESS_USER%:%ACCESS_TOKEN%@%CI_SERVER_HOST%/%CI_PROJECT_PATH%.git HEAD:%CI_COMMIT_REF_NAME%
    - echo Done
  artifacts:
    expire_in: 7 day
    paths:
      - ./build/index.html
      - ./build/manifest.json
      - ./build/favicon.ico
      - ./build/service-worker.js
      - ./build/asset-manifest.json
      - ./build/images/*.*
      - ./build/static/css/*.*
      - ./build/static/js/*.*
      - ./build/static/media/*.*
      - ./build/cesium/
  interruptible: true

deploy-qa-palermo:
  stage: deploy
  only:
    - develop
  tags:
    - palermo
  before_script:
    - chcp 65001
  script:
    - Write-Host "Deploying to QA environment..."
    - if(Test-Path $Env:deployDir) {Remove-Item $Env:deployDir -Recurse -Force}
    - New-Item -ItemType "directory" -Path $Env:deployDir
    - Copy-Item .\build\* -Destination $Env:deployDir -Recurse
    - Write-Host "Done"
  interruptible: true

deploy-qa-tokio:
  stage: deploy
  only:
    - develop
  tags:
    - tokio
  before_script:
    - chcp 65001
  script:
    - echo Deploying to QA environment...
    - rmdir /s /q %deployDir%
    - xcopy /E /C /I /Q /H /R /Y build %deployDir%
    - echo Done
  interruptible: true

#deploy-zip:
#  stage: deploy
#  <<: *base
#  script:
#    - echo Packing bundle into ZIP file...
#    - set jsonfile=package.json
#    - set psCmd="add-type -As System.Web.Extensions;$JSON = new-object Web.Script.Serialization.JavaScriptSerializer;$JSON.DeserializeObject($input).version"
#    - for /f %%I in ('^<"%jsonfile%" powershell -noprofile %psCmd%') do set "version=%%I"
#    - 'echo Version: %version%'
#    - set pack="WebmapFrontend_v%version%.zip"
#    - echo %pack%
#    - del /Q build\static\css\*.map
#    - del /Q build\static\js\*.map
#    - copy index.json .\build
#    - cd build
#    - echo Zipping...
#    - '"%exe7z%" a -tzip "%releaseDir%\%pack%" "*"'
#    - echo "copy to remote"
#    - call pscp -batch -pw %SSH_PASS% %releaseDir%\WebmapFrontend_v%version%.zip %SSH_USER_HOST%:%REMOTE_PATH%/%CURRENT_VERSION_MASTER%/
##  after_script:
##    - C:\Production\Version\curl-win\bin\curl.exe -s -X POST %TELEGRAM_URL% -d chat_id=%CHAT_ID% -d text=" %CI_PROJECT_NAME% %CI_JOB_NAME% Success"

#Increment_dzvin:
#  stage: increment-dzvin
#  <<: *base
#  script:
#    - echo run increment
#    - echo Done
#    - cd c:\Production\Version\install_update
#    - git checkout master
#    - git pull
#    - powershell.exe .\Versionalyze.ps1
#    - powershell.exe Start-sleep -s 10
#    - git commit -a -m "autocommit"
#    - git push https://%PUSH_USER%:%PUSH_TOKEN%@%push_version% HEAD:master
#  dependencies: []
