variables:
  yarn: 'C:\Program Files (x86)\Yarn\bin'

stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
    - webmap
  script: echo "TODO auto-test"

build:
  stage: build
  tags:
    - webmap
  script:
    - 'echo "Building project..."'
    - '$yarn\yarn.cmd install'
    - 'del .env'
    - 'copy .env.production .env'
    - 'call npm run-script build'
    - 'rmdir /s /q build\explorerLite'
    - 'del /Q build\static\css\*.map'
    - 'del /Q build\static\js\*.map'
    - 'git commit -a -m "autocommit inc-version after build"'
    - 'git push'
    - 'echo "Done!"'
  artifacts:
    paths:
      - build/index.html
      - build/static/css/main.*.css
      - build/static/js/main.*.js

deploy-qa:
  stage: deploy
  tags:
    - webmap
  script:
    - 'echo "Deploying to QA environment..."'
    - 'echo "Done!"'

deploy-zip:
  stage: deploy
  tags:
    - webmap
  script:
    - 'echo "Packing bundle into ZIP file..."'
    - 'echo "Done!"'
