export const CATALOG_FILTERS = 'catalog'
export const CATALOGS_FIELDS = 'catalogsFields'
export const SEARCH_FILTER = 'search'
export const MIL_SYMBOL_FILTER = 'milSymbolFilter'
export const LOADING = 'loading'
