export const CREATE = 'create'
export const EDIT = 'edit'
export const DEL = 'del'
export const DIVIDE_DIR = 'divide_direction'
export const COMBINE_DIR = 'combine_directions'
export const ZONE = 'zone'
export const ETERNAL = 'eternal'
