export const MIL_SYMBOL_FILTER_TYPE = 'MIL_SYMBOL_FILTER_TYPE'
export const CREATE_NEW_LAYER_TYPE = 'CREATE_NEW_LAYER_TYPE'
export const TOPOGRAPHIC_OBJECT_FILTER_TYPE = 'TOPOGRAPHIC_OBJECT_FILTER_TYPE'
