export const PRINT_PANEL_KEYS = {
  ID: 'id',
  SCALE: 'scale',
  MAP_LABEL: 'mapLabel',
  FIRST_ROW: 'firstRow',
  SECOND_ROW: 'secondRow',
  THIRD_ROW: 'thirdRow',
  FOURTH_ROW: 'fourthRow',
  FIFTH_ROW: 'fifthRow',
  START: 'start',
  FINISH: 'finish',
  INDICATOR_FIRST_ROW: 'indiFirst',
  INDICATOR_SECOND_ROW: 'indiSecond',
  INDICATOR_THIRD_ROW: 'indiThird',
  LEGEND_FIRST_COLOR: 'legendFirstColor',
  LEGEND_FIRST_CONTENT: 'legendFirstContent',
  LEGEND_SECOND_COLOR: 'legendSecondColor',
  LEGEND_SECOND_CONTENT: 'legendSecondContent',
  LEGEND_THIRD_COLOR: 'legendThirdColor',
  LEGEND_THIRD_CONTENT: 'legendThirdContent',
  LEGEND_FOURTH_COLOR: 'legendFourthColor',
  LEGEND_FOURTH_CONTENT: 'legendFourthContent',
}
