const SubordinationLevel = {
  TEAM_CREW: 'TEAM_CREW',
  SQUAD: 'SQUAD',
  SECTION: 'SECTION',
  PLATOON_DETACHMENT: 'PLATOON_DETACHMENT',
  COMPANY_BATTERY_TROOP: 'COMPANY_BATTERY_TROOP',
  BATTALION_SQUADRON: 'BATTALION_SQUADRON',
  REGIMENT_GROUP: 'REGIMENT_GROUP',
  BRIGADE: 'BRIGADE',
  DIVISION: 'DIVISION',
  CORPS_MEF: 'CORPS_MEF',
  ARMY: 'ARMY',
  ARMY_GROUP_FRONT: 'ARMY_GROUP_FRONT',
  REGION_THEATER: 'REGION_THEATER',
  COMMAND: 'COMMAND',
}

export default SubordinationLevel
