export const pointSignsList = 'pointSignsList'
export const mapSourcesList = 'mapSourcesList'
export const lineSignsList = 'lineSignsList'
export const subordinationLevel = 'subordinationLevel'
export const text = 'text'
export const print = 'print'
export const settings = 'settings'
export const directionName = 'directionName'
export const eternalPoint = 'eternalPoint'
export const map3D = 'map3D'
export const sidebarSelectedTabIndex = 'sidebarSelectedTabIndex'

export const zoneProfile = 'zoneProfile'
export const zoneVision = 'zoneVision'
